services:

  db:
    image: postgres:17
    environment:
      POSTGRES_USER: pharmacy
      POSTGRES_PASSWORD: pharmacy
      POSTGRES_DB: pharmacy_db
    ports:
      - "5433:5432"

  backend:
    build: ./backend
    ports:
      - "8001:8000"
    depends_on:
      - db
