# pharmacy_app/docker-compose.yml
services:

  db:
    image: postgres:17
    environment:
      POSTGRES_USER: majid
      POSTGRES_PASSWORD: linux113
      POSTGRES_DB: pharmacy_db
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    ports:
      - "8001:8000"
    depends_on:
      - db

volumes:
  postgres_data: