from enum import Enum


class Department(str, Enum):
    PHARMACEUTICAL = "PHARMACEUTICAL"
    COSMETICS = "COSMETICS"
    MEDICAL_EQUIPMENT = "MEDICAL_EQUIPMENT"
    OTC = "OTC"
    ORTHOPEDICS = "ORTHOPEDICS"
    SUPPLEMENTS = "SUPPLEMENTS"
    BABY_PRODUCTS = "BABY_PRODUCTS"
