from enum import Enum


class UserRole(str, Enum):
    ADMIN = "ADMIN"
    PHARMACIST = "PHARMACIST"
    OTC = "OTC"
    PRESCRIPTION = "PRESCRIPTION"
    COSMETICS = "COSMETICS"
    CASHIER = "CASHIER"
    WAREHOUSE = "WAREHOUSE"
    MEDICAL_EQUIPMENT = "MEDICAL_EQUIPMENT"
    PHARMACY_TECHNICIAN = "PHARMACY_TECHNICIAN"
    TRAINEE = "TRAINEE"
